### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by macaba** [enclave-networks/research.udp-perf#1]
Thank you for this nice bit of benchmarking code, I thought it was a neat solution for the lack of coverage in the .NET runtime.

It seems like you also ran across the issue that I and others have seen and documented here:
https://github.com/dotnet/runtime/issues/30797

I got curious so using your benchmarking app as a base (mainly the ThroughputCounter and related plumbing), I modified it to use [NanoSockets](https://github.com/nxrighthere/NanoSockets) to see  what gain (if any) in performance there would be without the cumbersome runtime problems in the way.

Using a PacketSize of 60000:

![image](https://user-images.githubusercontent.com/1031306/121558168-54bd2680-ca0d-11eb-8c95-1079fa247992.png)

That's a large gain! Food for thought perhaps.

**Comment by enclave-alistair** [comment]
Thanks @macaba, looks really interesting. Have you got a fork or something I could take a look at?

Also, what sort of transport network are you using there, 10Gbps Ethernet?

**Comment by macaba** [comment]
Quick and dirty:
https://github.com/macaba/research.udp-perf

Just a localhost connection, I get around 7Gbps under the same conditions using Enclave.UdpPerf.Test.

I suppose it's arguable as to whether NanoSockets is beneficial for the potential pain of interop so my hope is that the .NET runtime improvements will happen as a proper solution to stay fully managed.

**Comment by enclave-alistair** [comment]
Thanks for linking it; I'll take a look. 

Worth noting that localhost UDP data tends to have a very different perf profile to actual remote traffic, just due to the different path to the network stack?

Have you tried the small packet (1380 bytes) tests? It's the high pps test where the performance of the socket interop really impacts.

I to am looking forward to better performance from reduced-allocation connectionless sockets as per that issue.

**Comment by macaba** [comment]
Good point regarding localhost, I think the more realistic test will have to wait until I've got hardware.

Just tried 1380 bytes (still localhost)... 700Mbps with Enclave.UdpPerf.Test and 1200Mbps with NanoSockets. I think it's a reasonable guess to say that if reduced allocation improvements happen in the runtime, that gap will be reduced, perhaps eliminated. _fingers crossed_

**Comment by enclave-alistair** [comment]
Yeah, fingers crossed.  I'm hoping that the advent of HTTP3 (QUIC) support in ASP.NET Core, which has a UDP transport, will encourage better performance in the runtime.
