### ISSUE TITLE
Sending randomly generated integers, from server to client.

### ISSUE THREAD

**Issue by GevorDanielyan** [enclave-networks/research.udp-perf#2]
This is very good idea for using UDP protocol, for client server apps. But how we can send randomly generated integers from server to the client? For example in this part , you put packet size into buffer, as a meaningful data, but what if we want to send randomly generated integers?

```
private static async Task DoSendAsync(Socket udpSocket, IPEndPoint destination, ThroughputCounter throughput, CancellationToken cancelToken)
        {
            // Taking advantage of pre-pinned memory here using the .NET 5 POH (pinned object heap).            
            var buffer = GC.AllocateArray<byte>(PacketSize, true);
            var bufferMem = buffer.AsMemory();

            // Put something approaching meaningful data in the buffer.
            for (var idx = 0; idx < PacketSize; idx++)
            {
                bufferMem.Span[idx] = (byte)idx;
            }

            while (!cancelToken.IsCancellationRequested)
            {
                await udpSocket.SendToAsync(destination, bufferMem);

                throughput.Add(bufferMem.Length);
            }
        }
```

Thanks in advance.

**Comment by enclave-alistair** [comment]
You should just be able to combine the `RandomNumberGenerator` with a smaller buffer, and fill the buffer with the next random bytes from the generator before you send each packet. Something like:

```csharp
private static async Task DoSendAsync(Socket udpSocket, IPEndPoint destination, ThroughputCounter throughput, CancellationToken cancelToken)
{
    using var secureRandom = RandomNumberGenerator.Create();
    // Taking advantage of pre-pinned memory here using the .NET 5 POH (pinned object heap).            
    var buffer = GC.AllocateArray<byte>(sizeof(int), true);
    var bufferMem = buffer.AsMemory();

    while (!cancelToken.IsCancellationRequested)
    {
        // Randomly fill the buffer sized to a single int (4 bytes), with random values.
        secureRandom.GetBytes(bufferMem.Span);

        await udpSocket.SendToAsync(destination, bufferMem);

        throughput.Add(bufferMem.Length);
    }
}
```

**Comment by GevorDanielyan** [comment]
Ok, that's great. This generates random numbers and put it into buffer. But how we can see that generated random integers in this part of code, for example I need send generated numbers from server to client, and do some math statistic calculation in the client side. I need see that numbers in client side, in the console as well, to able do that math statistic calculations.

Thanks in advance @enclave-alistair 

`private static async Task PrintThroughput(ThroughputCounter counter, CancellationToken cancelToken)
        {
            while (!cancelToken.IsCancellationRequested)
            {
                await Task.Delay(1000, cancelToken);

                var count = counter.SampleAndReset();

                var megabytes = count / 1024d / 1024d;

                double pps = count / PacketSize;

                Console.WriteLine("{0:0.00}MBps ({1:0.00}Mbps) - {2:0.00}pps", megabytes, megabytes * 8, pps);
            }
        }`

**Comment by enclave-alistair** [comment]
You can use the `BinaryPrimitives` class to read numbers from byte buffers; update `DoReceiveAsync` with a call to extract a number from each packet:

```csharp
var result = await udpSocket.ReceiveFromAsync(bufferMem);

// The result tells me where it came from, and gives me the data.
if (result is SocketReceiveFromResult recvResult)
{
    // Read a 32-bit integer from the buffer.
    if (BinaryPrimitives.TryReadInt32LittleEndian(bufferMem.Span, out var number))
    {
        // number is the random value sent to this socket.
    }
}
else
{
    break;
}
```

Once you've got the number from the socket, you can do whatever you need to with those values.

**Comment by GevorDanielyan** [comment]
From the bufferMem.Span we get 4 random integers, which we need to write in number, and the variable number  will take on 4 different values, I need to add those 4 values at the same time, for example in the List<int> and do some math calculations․ How can I get this 4 different values. Thanks in advance @enclave-alistair ))

**Comment by enclave-alistair** [comment]
If I understand correctly, just move the span along by getting a new span with `bufferMem.Span.Slice(sizeof(int))`.  That will give you a new span just after the position of the current value.

**Comment by GevorDanielyan** [comment]
I mean, in the bufferMem.Span we have 4 different random numbers, I need to add that 4 numbers for example in the List<int>, and send that List to some Math Calculation, I need retrieve number's at the same time.

if (BinaryPrimitives.TryReadInt32LittleEndian(bufferMem.Span, out var number))
    {
        // number is the random value sent to this socket.
        List<int> randomNumbers = new List<int>();
        randomNumbers.Add(number); //Fore example like this
    }

**Comment by enclave-alistair** [comment]
You need to call `TryReadInt32LittleEndian` once for each number you want to read, and read a different part of the span using the slice mechanism I described above.

**Comment by GevorDanielyan** [comment]
Dear @enclave-alistair  ,
Could you write example ? Thanks ))

**Comment by GevorDanielyan** [comment]
I wrote like this.

```
if (result is SocketReceiveFromResult recvResult)
                    {
                        List<int> randomNumbers = new();

                        for (int i = 0; i < bufferMem.Span.Length; i++)
                        {
                            BinaryPrimitives.TryReadInt32LittleEndian(bufferMem.Span, out var number);
                            randomNumbers.Add(number);
                            bufferMem.Span[i]++;
                        }

                        throughput.Add(recvResult.ReceivedBytes);
                    }
```

**Comment by enclave-alistair** [comment]
Close, but it's more like:

```csharp
if (result is SocketReceiveFromResult recvResult)
{
    List<int> randomNumbers = new();

    var readSpan = bufferMem.Span;

    while(readSpan.Length > 0)
    {
        if (BinaryPrimitives.TryReadInt32LittleEndian(readSpan, out var number))
        {        
            randomNumbers.Add(number);
        }

        readSpan = readSpan.Slice(sizeof(int));
    }
}
```

**Comment by GevorDanielyan** [comment]
> Close, but it's more like:
> 
> ```cs
> if (result is SocketReceiveFromResult recvResult)
> {
>     List<int> randomNumbers = new();
> 
>     var readSpan = bufferMem.Span;
> 
>     while(readSpan.Length > 0)
>     {
>         if (BinaryPrimitives.TryReadInt32LittleEndian(readSpan, out var number))
>         {        
>             randomNumbers.Add(number);
>         }
> 
>         readSpan = readSpan.Slice(sizeof(int));
>     }
> }
> ```

But we can't declare variable like `var readSpan = bufferMem.Span;` in async method.
