### ISSUE TITLE
Feedback -  Cancelation Support

### ISSUE THREAD

**Issue by Simonl9l** [enclave-networks/research.udp-perf#3]
Hi @enclave-alistair 

Very interesting approach! 

I notice that the call to `ReceiveFromAsync` in the `UdpAwaitableSocketAsyncEventArgs:DoReceiveFromAsync` and send equivalents don't take a cancelation token in given the Socket class, but do delegate to a private function that does!

As such once the code in in here waiting for a packet, its blocking the task with no way to cancel it. 

```
 public bool ReceiveFromAsync(SocketAsyncEventArgs e) => ReceiveFromAsync(e, default);

private bool ReceiveFromAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken)
{
   ..
}
```

There are (now with net 6) [other](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.receivefromasync?view=net-6.0) versions of this method, that were not available before, that take different parameters including cancelation tokens.

However to use them it this seems to mean a full refactor, and am still doing 0-100 of understanding all this. Would you be able to make any recommendation on such a refactor to be able to pass in a cancelation token given the above limitation of the DotNet Socket implementation (Net 6).

I'm are concerned with the Receive path as this as a server will sit and block where as the send path is mostly an instantaneous call.

Thanks!

**Comment by Simonl9l** [comment]
@enclave-alistair I really appreciate you jumping on this! I just tested it, and cancelation support now works!

I'm curious that all the changes are just in the Socket Extension not in the  AwaitableSockets implementation.

as a side note you might want to add the ` /// <param name="cancelToken">A CancellationToken </param> ` comment into each socket extension method headers.

I have a scenario where there is a need to send out multiple UDP packets to different endpoints "simultaneously" (using `Task.WhenAll`) so this if I get it will take advantage of your pooling.

**Comment by enclave-alistair** [comment]
@Simonl9l, took a while, but have posted an updated blog post and made the necessary changes in this repo for .net6: https://enclave.io/high-performance-udp-sockets-net6/
